version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: local_mssql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: local_mqtt
    restart: always
    ports:
      - "1883:1883"   # MQTT
      - "9001:9001"   # WebSocket (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      
  api:
    profiles: ["full", "full-simulator"]
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: api_service
    restart: always
    ports:
      - "5050:8080"
    depends_on:
      - db
      - mqtt
    environment:
      - ASPNETCORE_ENVIRONMENT=LocalDocker
      
  dataconsumer:
    profiles: ["full", "full-simulator"]
    build:
      context: .
      dockerfile: DataConsumer/Dockerfile
    container_name: dataconsumer_service
    restart: always
    depends_on:
      - db
      - mqtt
      - api
    environment:
      - MQTT__Host=mqtt
      - MQTT__Port=1883
      - DOTNET_ENVIRONMENT=LocalDocker

  mqtt-simulator:
    profiles: ["full-simulator"]
    build:
      context: .
      dockerfile: IoTSimulator/Dockerfile
    container_name: greenhouse_simulator
    restart: always
    depends_on:
      - db
      - mqtt
      - api
      - dataconsumer  
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - SENSOR_INTERVAL=60


volumes:
  mssql_data: