// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250514154727_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Entities.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GreenhouseId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GreenhouseId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("Data.Entities.Greenhouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivePresetId")
                        .HasColumnType("int");

                    b.Property<string>("FertilizationMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LightingMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WateringMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivePresetId");

                    b.HasIndex("UserEmail");

                    b.ToTable("Greenhouses");
                });

            modelBuilder.Entity("Data.Entities.Preset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HoursOfLight")
                        .HasColumnType("int");

                    b.Property<double>("MaxAirHumidity")
                        .HasColumnType("float");

                    b.Property<double>("MaxSoilHumidity")
                        .HasColumnType("float");

                    b.Property<double>("MaxTemperature")
                        .HasColumnType("float");

                    b.Property<double>("MinAirHumidity")
                        .HasColumnType("float");

                    b.Property<double>("MinSoilHumidity")
                        .HasColumnType("float");

                    b.Property<double>("MinTemperature")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SystemPresetId")
                        .HasColumnType("int");

                    b.Property<int?>("UserPresetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemPresetId");

                    b.HasIndex("UserPresetId");

                    b.ToTable("Presets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HoursOfLight = 12,
                            MaxAirHumidity = 60.0,
                            MaxSoilHumidity = 50.0,
                            MaxTemperature = 25.0,
                            MinAirHumidity = 40.0,
                            MinSoilHumidity = 30.0,
                            MinTemperature = 18.0,
                            Name = "Default System Preset"
                        });
                });

            modelBuilder.Entity("Data.Entities.User", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GreenhouseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GreenhouseId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NotificationUser", b =>
                {
                    b.Property<int>("NotificationsId")
                        .HasColumnType("int");

                    b.Property<string>("Usersemail")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationsId", "Usersemail");

                    b.HasIndex("Usersemail");

                    b.ToTable("NotificationUser");
                });

            modelBuilder.Entity("SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GreenhouseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GreenhouseId");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("SystemPreset", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SystemPresets");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("UserPreset", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail");

                    b.ToTable("UserPresets");
                });

            modelBuilder.Entity("Data.Entities.Action", b =>
                {
                    b.HasOne("Data.Entities.Greenhouse", "Greenhouse")
                        .WithMany("Actions")
                        .HasForeignKey("GreenhouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Greenhouse");
                });

            modelBuilder.Entity("Data.Entities.Greenhouse", b =>
                {
                    b.HasOne("Data.Entities.Preset", "ActivePreset")
                        .WithMany("Greenhouses")
                        .HasForeignKey("ActivePresetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Data.Entities.User", "User")
                        .WithMany("Greenhouses")
                        .HasForeignKey("UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivePreset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.Preset", b =>
                {
                    b.HasOne("SystemPreset", "SystemPreset")
                        .WithMany()
                        .HasForeignKey("SystemPresetId");

                    b.HasOne("UserPreset", "UserPreset")
                        .WithMany()
                        .HasForeignKey("UserPresetId");

                    b.Navigation("SystemPreset");

                    b.Navigation("UserPreset");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.HasOne("Data.Entities.Greenhouse", "Greenhouse")
                        .WithMany("Notifications")
                        .HasForeignKey("GreenhouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Greenhouse");
                });

            modelBuilder.Entity("NotificationUser", b =>
                {
                    b.HasOne("Notification", null)
                        .WithMany()
                        .HasForeignKey("NotificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("Usersemail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SensorReading", b =>
                {
                    b.HasOne("Data.Entities.Greenhouse", "Greenhouse")
                        .WithMany("SensorReadings")
                        .HasForeignKey("GreenhouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Greenhouse");
                });

            modelBuilder.Entity("SystemPreset", b =>
                {
                    b.HasOne("Data.Entities.Preset", "Preset")
                        .WithOne()
                        .HasForeignKey("SystemPreset", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("UserPreset", b =>
                {
                    b.HasOne("Data.Entities.Preset", "Preset")
                        .WithOne()
                        .HasForeignKey("UserPreset", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.User", "User")
                        .WithMany("UserPresets")
                        .HasForeignKey("UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.Greenhouse", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Notifications");

                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("Data.Entities.Preset", b =>
                {
                    b.Navigation("Greenhouses");
                });

            modelBuilder.Entity("Data.Entities.User", b =>
                {
                    b.Navigation("Greenhouses");

                    b.Navigation("UserPresets");
                });
#pragma warning restore 612, 618
        }
    }
}
