name: Deploy Data Consumer to Azure

on:
  workflow_run:
    workflows: ["Continous Deployment"]
    types:
      - completed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_dataconsumer:
    name: Deploy Data Consumer to Azure
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Azure login with managed identity
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Get latest image tag
        id: get_tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "image_tag=latest" >> $GITHUB_OUTPUT
          else
            echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Deploy to Container App
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az containerapp update \
              --name gh-dataconsumer-app \
              --resource-group green-house-rg \
              --image ghcr.io/${{ github.repository_owner }}/greenhouse-dataconsumer:${{ steps.get_tag.outputs.image_tag }} \
      
      - name: Logout from Azure
        run: |
          az logout