name: Continous Deployment

on:
  push:
    branches:
      - main
      - feature/pipelines
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write  # Required for Azure authentication

jobs:
  build_api:
    uses: ./.github/workflows/.build-docker-image.yml
    with:
      image_name: 'greenhouse-api'
      image_tag: ${{ github.sha }}
      dockerfile_location: './Api/Dockerfile'
      docker_context: '.'  
      push_to_registry: 'true'
  build_dataconsumer:
    uses: ./.github/workflows/.build-docker-image.yml
    with:
      image_name: 'greenhouse-dataconsumer'
      image_tag: ${{ github.sha }}
      dockerfile_location: './DataConsumer/Dockerfile'
      docker_context: '.'  
      push_to_registry: 'true'

  deploy_dataconsumer:
    name: Deploy Data Consumer to Azure
    needs: build_dataconsumer
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Azure login with managed identity
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Deploy to Container App
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az containerapp update \
              --name gh-dataconsumer-app75058916 \
              --resource-group green-house-rg \
              --image ghcr.io/${{ github.repository_owner }}/greenhouse-dataconsumer:${{ github.sha }}
      
      - name: Logout from Azure
        run: |
          az logout

  deploy_api:
    name: Deploy API to Azure
    needs: build_api
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Azure login with managed identity
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Deploy to Container App
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az containerapp update \
              --name gh-dataconsumer-app75058916 \
              --resource-group green-house-rg \
              --image ghcr.io/${{ github.repository_owner }}/greenhouse-api:${{ github.sha }}
      
      - name: Logout from Azure
        run: |
          az logout